# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Str8line Tattoo & Body Piercings
email: str8line@embarqmail.com
description: > # this means to ignore newlines until "baseurl:"
  Str8line Tattoo takes pride in providing the best services and satisfying our customer needs. 
  We specialize in tattoos and body piercings. Our tattoo styles range from portraits and 
  watercolors to mandalas and traditional. We perform body piercings of all kinds, excluding dermals.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://str8linetattoo.com" # the base hostname & protocol for your site

# Includes an icon in the footer for each username you enter
footer-links:
  dribbble:
  email: str8line@embarqmail.com
  facebook: str8linetattoo
  flickr:
  github:
  instagram: str8line_tattoo
  linkedin:
  pinterest:
  rss:
  twitter: str8linetattoo
  stackoverflow:
  youtube:
  googleplus: +Str8lineTattooFortMyers

# Build settings
markdown: kramdown
